backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "post"
    label: "Post"
    folder: "posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}